# Generated by Django 3.2.12 on 2022-09-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agent_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_prepaid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superadmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superteller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
