# Generated by Django 3.2.12 on 2022-09-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220904_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('client', 'client')], max_length=50, null=True),
        ),
    ]
